<?php

namespace ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AddFieldPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddFieldPageRepository extends EntityRepository
{
}
