stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            sluggable: true
            timestampable: true
            blameable:      ~
            translatable: true
            loggable:       ~
            softdeleteable: ~
            uploadable:     ~
