sonata_user:
    manager_type: orm # can be orm or mongodb

#    impersonating:
#        route:                page_slug
#        parameters:           { path: / }

#    profile:
#        menu:
#            - { route: 'sonata_user_profile_edit', label: 'link_edit_profile', domain: 'SonataUserBundle'}
#            - { route: 'sonata_user_profile_edit_authentication', label: 'link_edit_authentication', domain: 'SonataUserBundle'}

        # Profile Form (firstname, lastname, etc ...)
#        form:
#            type:               sonata_user_profile
#            handler:            sonata.user.profile.form.handler.default
#            name:               sonata_user_profile_form
#            validation_groups:  [Profile]