services:
    sonata.admin.product:
        class: ShopBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Product }
        arguments:
            - ~
            - ShopBundle\Entity\Product
            - ~

    shop.admin.category:
        class: ShopBundle\Admin\CategoryAdmin
        arguments: [~, ShopBundle\Entity\Category, ShopBundle:CategoryAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Category}

    shop.admin.page:
        class: ShopBundle\Admin\PageAdmin
        arguments: [~, ShopBundle\Entity\Page, ShopBundle:PageAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Page}

    shop.admin.product_characteristic:
        class: ShopBundle\Admin\ProductCharacteristicAdmin
        arguments: [~, ShopBundle\Entity\ProductCharacteristic, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Product–°haracteristic}

    shop.admin.characteristic:
        class: ShopBundle\Admin\CharacteristicAdmin
        arguments: [~, ShopBundle\Entity\Characteristic, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Characteristic}
