services:
    sonata.admin.post:
        class: ShopBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Product", label: "Post" }
        arguments:
            - ~
            - ShopBundle\Entity\Product
            - ~