shop_homepage:
    path:     /
    defaults: { _controller: ShopBundle:Default:index }

shop_product:
    path:     /{category}/{id}
    defaults: { _controller: ShopBundle:Default:product }

shop_categories:
    path:     /categories
    defaults: { _controller: ShopBundle:Default:categories }

shop_category:
    path:     /category
    defaults: { _controller: ShopBundle:Default:category }

shop_about_us:
    path:     /about
    defaults: { _controller: ShopBundle:Default:aboutUs }
