shop_homepage:
    path:     /
    defaults: { _controller: ShopBundle:Default:index }

shop_product:
    path:     /{category_slug}/item/{slug}/
    defaults: { _controller: ShopBundle:Default:product }

shop_category:
    path:     /category/{category_slug}
    defaults: { _controller: ShopBundle:Default:category }

shop_about_us:
    path:     /about
    defaults: { _controller: ShopBundle:Default:aboutUs }

shop_contact_us:
    path:     /contact-us
    defaults: { _controller: ShopBundle:Default:contactUs }